/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dk.pop.srs.usecases.slebetaler;

import dk.pop.srs.betaler.Betaler;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author patrick
 */
public class SLEBGUI extends javax.swing.JDialog {

    private SLEBHandler sLEBHandler;
    private String[] columnNames = {"BetalerCPR", "BetalerNavn"};
    
    public SLEBGUI(java.awt.Frame parent, boolean modal, SLEBHandler sLEBHandler) {
        super(parent, modal);
        this.sLEBHandler = sLEBHandler;
        setLookAndFeel();
        initComponents();
        setFrame();
        setTableRules();
    }
    
    /**
     * Sets jDialog location to middle of the screen
     */
    private void setFrame() {
        setLocationRelativeTo(null);
    }

    /**
     * Set look and feel
     */
    private void setLookAndFeel() {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SLEBGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>>
    }

    /**
     * Set table rules
     */
    public void setTableRules() {
        betalere_table.getTableHeader().setReorderingAllowed(false);

    }
    
    /**
     * Get personer and set them to the table model
     * @param ignoreError 
     */
    private void hentBetalere(boolean ignoreError) {
        String value = betaler_textField.getText();
        ArrayList<Betaler> betalere;
        if (!value.isEmpty()) {
            betalere = sLEBHandler.getBetalerV2(value);



            if (!betalere.isEmpty()) {
                betalere_table.setEnabled(true);
                DefaultTableModel dtm = new DefaultTableModel();
                for (String s : columnNames) {
                    dtm.addColumn(s);
                }

                for (Betaler b : betalere) {
                    String[] a = {b.getBetalingCPR(), b.getBetalingNavn()};
                    dtm.addRow(a);
                }
                betalere_table.setModel(dtm);
            } else {
                DefaultTableModel dtm = new DefaultTableModel();
                for (String s : columnNames) {
                    dtm.addColumn(s);

                }
                betalere_table.setModel(dtm);
                if (!ignoreError) {
                    JOptionPane.showMessageDialog(this, "Betalerne blev ikke fundet\nHar du tastet rigtigt?", "Fejl", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        else{
            betalere = sLEBHandler.getAlleBetalere();
            betalere_table.setEnabled(true);
                DefaultTableModel dtm = new DefaultTableModel();
                for (String s : columnNames) {
                    dtm.addColumn(s);
                }

                for (Betaler b : betalere) {
                    String[] a = {b.getBetalingCPR(), b.getBetalingNavn()};
                    dtm.addRow(a);
                }
                betalere_table.setModel(dtm);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_pane2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        betaler_textField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        betalere_table = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        hentPersoner_button = new javax.swing.JButton();
        luk_button = new javax.swing.JButton();
        sletPerson_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel3.setText("BetalerCPR/BetalerNavn");

        betaler_textField.setToolTipText("CPR skal være på 10 tegn");
        betaler_textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                betaler_textFieldActionPerformed(evt);
            }
        });
        betaler_textField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                betaler_textFieldKeyReleased(evt);
            }
        });

        betalere_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        betalere_table.setEnabled(false);
        betalere_table.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                betalere_tableFocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(betalere_table);

        jLabel4.setText("Betalere");

        hentPersoner_button.setText("Find betaler");
        hentPersoner_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hentPersoner_buttonActionPerformed(evt);
            }
        });

        luk_button.setText("Luk");
        luk_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luk_buttonActionPerformed(evt);
            }
        });

        sletPerson_button.setText("Slet betaler");
        sletPerson_button.setEnabled(false);
        sletPerson_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sletPerson_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout main_pane2Layout = new javax.swing.GroupLayout(main_pane2);
        main_pane2.setLayout(main_pane2Layout);
        main_pane2Layout.setHorizontalGroup(
            main_pane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_pane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(main_pane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(main_pane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(main_pane2Layout.createSequentialGroup()
                        .addComponent(luk_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sletPerson_button)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(main_pane2Layout.createSequentialGroup()
                        .addComponent(betaler_textField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hentPersoner_button))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE))
                .addContainerGap())
        );
        main_pane2Layout.setVerticalGroup(
            main_pane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_pane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(main_pane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(betaler_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hentPersoner_button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(main_pane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(main_pane2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 189, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(main_pane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sletPerson_button)
                    .addComponent(luk_button))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_pane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_pane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void betaler_textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_betaler_textFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_betaler_textFieldActionPerformed

    private void betaler_textFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_betaler_textFieldKeyReleased

    }//GEN-LAST:event_betaler_textFieldKeyReleased

    private void betalere_tableFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_betalere_tableFocusGained
        sletPerson_button.setEnabled(true);
    }//GEN-LAST:event_betalere_tableFocusGained

    private void hentPersoner_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hentPersoner_buttonActionPerformed
        hentBetalere(false);
    }//GEN-LAST:event_hentPersoner_buttonActionPerformed

    private void luk_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luk_buttonActionPerformed
        this.dispose();
    }//GEN-LAST:event_luk_buttonActionPerformed

    private void sletPerson_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sletPerson_buttonActionPerformed
        int selection = betalere_table.getSelectedRow();
        String value = betaler_textField.getText();
        ArrayList<Betaler> betalere = sLEBHandler.getBetalerV2(value);

        Betaler toDelete = betalere.get(selection);

        int n = JOptionPane.showConfirmDialog(this, "Er du sikker på du vil slette den valgte betaler?\nADVARSEL, denne handling kan ikke gøres om!", "Slet betaler?", JOptionPane.YES_NO_OPTION);
        if (n == 0) {
            if (sLEBHandler.sletBetaler(toDelete)) {
                hentBetalere(true);
                JOptionPane.showMessageDialog(this, "Betaleren blev slettet!", "Slettet!", JOptionPane.PLAIN_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Du skal slette alle betalerens sager før du kan slette betaleren", "Fejl", JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_sletPerson_buttonActionPerformed
//
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(SLEBGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(SLEBGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(SLEBGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(SLEBGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                SLEBGUI dialog = new SLEBGUI(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField betaler_textField;
    private javax.swing.JTable betalere_table;
    private javax.swing.JButton hentPersoner_button;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton luk_button;
    private javax.swing.JPanel main_pane2;
    private javax.swing.JButton sletPerson_button;
    // End of variables declaration//GEN-END:variables
}
