/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dk.pop.srs.usecases.slesag;

import dk.pop.srs.sag.Sag;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Patrick
 */
public class SLEGUI extends javax.swing.JDialog {

    private SLEHandler sLEHandler;
    private String[] columnNames = {"CPR", "Sagssted", "Paragraf", "Foranstaltningsnavn", "Beskrivelse", "PeriodeFra", "PeriodeTil", "AER", "Sagstype", "BetalingCPR", "BetalingBeløb"};

    public SLEGUI(java.awt.Frame parent, boolean modal, SLEHandler sLEHandler) {
        super(parent, modal);
        this.sLEHandler = sLEHandler;
        setLookAndFeel();
        initComponents();
        setFrame();
        setTableRules();
    }

    private void setLookAndFeel() {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SLEGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>>
    }

    private void setFrame() {
        setLocationRelativeTo(null);
    }
    
    public void setTableRules() {
        sager_table.getTableHeader().setReorderingAllowed(false);
    }

    private void reset() {
        cpr_textField.setText("");
        sager_table.setModel(new DefaultTableModel());
        sletSag_button.setEnabled(false);
        sager_table.setEnabled(false);
        hentSager_button.setEnabled(false);
    }

    private void hentSager() {
        String cpr = cpr_textField.getText();

        if (cpr.length() == 10) {
            if (sLEHandler.checkPersonExists(cpr)) {
                sager_table.setEnabled(true);
                ArrayList<Sag> sager = sLEHandler.sogCPR(cpr, false);
                if (!sager.isEmpty()) {
                    DefaultTableModel dtm = new DefaultTableModel();
                    for (String s : columnNames) {
                        dtm.addColumn(s);
                    }

                    for (Sag s : sager) {
                        String[] a = {s.getPerson().getCpr(), s.getSagsSted(), s.getParagraf(), s.getForanstaltningsnavn(), s.getBeskrivelse(), String.valueOf(s.getPeriodeFra()), String.valueOf(s.getPeriodeTil()), String.valueOf(s.getAer()), String.valueOf(s.getSagstype()), s.getBetaler().getBetalingCPR(), String.valueOf(s.getBetalingBelob())};
                        dtm.addRow(a);
                    }
                    sager_table.setModel(dtm);
                } else {
                    DefaultTableModel dtm = new DefaultTableModel();
                    for (String s : columnNames) {
                        dtm.addColumn(s);
                    }
                    sager_table.setModel(dtm);
                }
            } else {
                JOptionPane.showMessageDialog(this, "CPR nummeret blev ikke fundet\nHar du tastet rigtigt?", "Fejl", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Der er sket en fejl fordi en af følgende ikke er blevet overholdt:\n- CPR nummer skal være på 10 tegn", "Fejl", JOptionPane.ERROR_MESSAGE);
        }
    }

    public String removeLetters(String text) {
        return text.replaceAll("[^0-9]", "");
    }

    public String removeLettersV2(String text) {
        return text.replaceAll("[^0-9.,]", "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_pane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cpr_textField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        sager_table = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        hentSager_button = new javax.swing.JButton();
        luk_button = new javax.swing.JButton();
        sletSag_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Slet sag");
        setMinimumSize(new java.awt.Dimension(300, 300));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("CPR");

        cpr_textField.setToolTipText("CPR skal være på 10 tegn");
        cpr_textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpr_textFieldActionPerformed(evt);
            }
        });
        cpr_textField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cpr_textFieldKeyReleased(evt);
            }
        });

        sager_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        sager_table.setEnabled(false);
        sager_table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        sager_table.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                sager_tableFocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(sager_table);

        jLabel2.setText("Sager");

        hentSager_button.setText("Hent sager");
        hentSager_button.setEnabled(false);
        hentSager_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hentSager_buttonActionPerformed(evt);
            }
        });

        luk_button.setText("Luk");
        luk_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luk_buttonActionPerformed(evt);
            }
        });

        sletSag_button.setText("Slet sag");
        sletSag_button.setEnabled(false);
        sletSag_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sletSag_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout main_paneLayout = new javax.swing.GroupLayout(main_pane);
        main_pane.setLayout(main_paneLayout);
        main_paneLayout.setHorizontalGroup(
            main_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(main_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(main_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(main_paneLayout.createSequentialGroup()
                        .addComponent(luk_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sletSag_button)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(main_paneLayout.createSequentialGroup()
                        .addComponent(cpr_textField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hentSager_button))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1074, Short.MAX_VALUE))
                .addContainerGap())
        );
        main_paneLayout.setVerticalGroup(
            main_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(main_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cpr_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hentSager_button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(main_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(main_paneLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 489, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(main_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sletSag_button)
                    .addComponent(luk_button))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_pane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_pane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void luk_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luk_buttonActionPerformed
        this.dispose();
    }//GEN-LAST:event_luk_buttonActionPerformed

    private void hentSager_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hentSager_buttonActionPerformed
        hentSager();
    }//GEN-LAST:event_hentSager_buttonActionPerformed

    private void cpr_textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpr_textFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpr_textFieldActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        reset();
    }//GEN-LAST:event_formWindowClosed

    private void sager_tableFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sager_tableFocusGained
        sletSag_button.setEnabled(true);
    }//GEN-LAST:event_sager_tableFocusGained

    private void sletSag_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sletSag_buttonActionPerformed
        int selection = sager_table.getSelectedRow();
        String cpr = cpr_textField.getText();
        ArrayList<Sag> sager = sLEHandler.sogCPR(cpr.replace("-", ""), false);

        Sag toDelete = sager.get(selection);
        int n = JOptionPane.showConfirmDialog(this, "Er du sikker på du vil slette den valgte sag?\nADVARSEL, denne handling kan ikke gøres om!", "Slet sag?", JOptionPane.YES_NO_OPTION);
        if (n == 0) {
            sLEHandler.sletSag(toDelete);
            hentSager();
            JOptionPane.showMessageDialog(this, "Sagen blev slettet!", "Slettet!", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_sletSag_buttonActionPerformed

    private void cpr_textFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cpr_textFieldKeyReleased
        cpr_textField.setText(removeLetters(cpr_textField.getText()));

        if (cpr_textField.getText().length() == 0) {
            hentSager_button.setEnabled(false);
        } else {
            hentSager_button.setEnabled(true);
        }
    }//GEN-LAST:event_cpr_textFieldKeyReleased
//
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(SLEGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(SLEGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(SLEGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(SLEGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                SLEGUI dialog = new SLEGUI(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cpr_textField;
    private javax.swing.JButton hentSager_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton luk_button;
    private javax.swing.JPanel main_pane;
    private javax.swing.JTable sager_table;
    private javax.swing.JButton sletSag_button;
    // End of variables declaration//GEN-END:variables
}
